if(NOT DEFINED RESULT_PREFIX)
    message(FATAL_ERROR "RESULT_PREFIX was not supplied")
endif()

foreach(kind nodes links tanks summary)
    if(NOT EXISTS "${RESULT_PREFIX}-${kind}.csv")
        message(FATAL_ERROR "Missing controlled EPS output: ${RESULT_PREFIX}-${kind}.csv")
    endif()
endforeach()

file(READ "${RESULT_PREFIX}-summary.csv" summary)
if(NOT summary MATCHES "simple_controls,8")
    message(FATAL_ERROR "Not all EPANET simple controls were parsed")
endif()
if(NOT summary MATCHES "hydraulic_states,33")
    message(FATAL_ERROR "The EPS scheduler did not stop at every off-grid control event")
endif()
if(NOT summary MATCHES "failed_states,0")
    message(FATAL_ERROR "The controlled EPS test did not converge")
endif()

file(READ "${RESULT_PREFIX}-links.csv" links)
if(NOT links MATCHES "3600,Timed,PIPE,[^\n]*,0,1")
    message(FATAL_ERROR "AT TIME did not close the controlled pipe")
endif()
if(NOT links MATCHES "7200,Timed,PIPE,[^\n]*,1,1")
    message(FATAL_ERROR "AT TIME did not reopen the controlled pipe")
endif()
if(NOT links MATCHES "3600,Clock,PIPE,[^\n]*,0,1")
    message(FATAL_ERROR "AT CLOCKTIME did not account for START CLOCKTIME")
endif()
if(NOT links MATCHES "7200,Clock,PIPE,[^\n]*,1,1")
    message(FATAL_ERROR "The later AT CLOCKTIME control was not applied")
endif()
if(NOT links MATCHES "90000,Clock,PIPE,[^\n]*,0,1")
    message(FATAL_ERROR "AT CLOCKTIME did not recur on the next day")
endif()
if(NOT links MATCHES "93600,Clock,PIPE,[^\n]*,1,1")
    message(FATAL_ERROR "The recurring clock control did not reopen the pipe")
endif()
if(NOT links MATCHES "0,Pressure,PIPE,[^\n]*,0,1")
    message(FATAL_ERROR "ABOVE pressure control or KPA conversion failed")
endif()
if(NOT links MATCHES "0,LowPress,PIPE,[^\n]*,0,1")
    message(FATAL_ERROR "BELOW pressure control or KPA conversion failed")
endif()
if(NOT links MATCHES "3600,PSet,PUMP,[^\n]*,0\\.012[0-9]*,nan,[^\n]*,1,1")
    message(FATAL_ERROR "Numeric pump setting was not retained")
endif()
if(NOT links MATCHES "7200,PSet,PUMP,[^\n]*,0\\.038[0-9]*,nan,[^\n]*,1,1")
    message(FATAL_ERROR "Numeric pump setting was not restored")
endif()
