if(NOT DEFINED RESULT_PREFIX)
    message(FATAL_ERROR "RESULT_PREFIX was not supplied")
endif()

file(READ "${RESULT_PREFIX}-summary.csv" summary)
if(NOT summary MATCHES "simple_controls,3")
    message(FATAL_ERROR "Not all TCV controls were parsed")
endif()
if(NOT summary MATCHES "hydraulic_states,4")
    message(FATAL_ERROR "The TCV EPS test did not produce four hourly states")
endif()
if(NOT summary MATCHES "failed_states,0")
    message(FATAL_ERROR "The TCV EPS test did not converge")
endif()

file(READ "${RESULT_PREFIX}-links.csv" links)
if(NOT links MATCHES "0,TCV1,VALVE,[^\n]*,1,1")
    message(FATAL_ERROR "The imported TCV was not active at time zero")
endif()
if(NOT links MATCHES "3600,TCV1,VALVE,[^\n]*,1,1")
    message(FATAL_ERROR "The numeric TCV setting control was not applied")
endif()
if(NOT links MATCHES "7200,TCV1,VALVE,[^\n]*,1,1")
    message(FATAL_ERROR "The OPEN TCV control was not applied")
endif()
if(NOT links MATCHES "10800,TCV1,VALVE,[^\n]*,1,1")
    message(FATAL_ERROR "The ACTIVE TCV control was not applied")
endif()

# With Q = 0.001 m3/s and D = 0.02 m, the expected head losses are
# K*v^2/(2g): approximately 1.033 m (K=2), 4.131 m (K=8),
# 0.258 m (OPEN minor loss K=0.5), and 4.131 m (ACTIVE again).
if(NOT links MATCHES "0,TCV1,VALVE,[^\n]*,1\\.03[0-9]*,1,1")
    message(FATAL_ERROR "Initial TCV head loss does not match K*v^2/(2g)")
endif()
if(NOT links MATCHES "3600,TCV1,VALVE,[^\n]*,4\\.13[0-9]*,1,1")
    message(FATAL_ERROR "Numeric TCV setting did not update the head loss")
endif()
if(NOT links MATCHES "7200,TCV1,VALVE,[^\n]*,0\\.25[0-9]*,1,1")
    message(FATAL_ERROR "OPEN TCV did not use the separate minor-loss coefficient")
endif()
if(NOT links MATCHES "10800,TCV1,VALVE,[^\n]*,4\\.13[0-9]*,1,1")
    message(FATAL_ERROR "ACTIVE TCV did not restore the controlled setting")
endif()
